# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            asset_name: linux-furina
            dumbass_zip: unzip 
            dumbass_move: mv
          - os: windows-latest
            asset_name: win-furina
            dumbass_zip: tar -xf
            dumbass_move: move
        
    steps:
    - uses: actions/checkout@v3
    - name: Build setup
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Download Source
      run: |
        mkdir tmp
        cd tmp
        curl https://fire.redz.workers.dev/ -o gaming.zip
        ${{ matrix.dumbass_zip }} gaming.zip
        
    - name: Restore dependencies
      working-directory: ./tmp/furinaimpact
      run: dotnet restore
      
    - name: Build
      working-directory: ./tmp/furinaimpact
      run: dotnet build --no-restore --configuration Release

    - name: Clean Build
      working-directory: ./tmp/furinaimpact
      run: |
        mkdir ./build
        mkdir ./build/Server
        mkdir ./build/Proxy        
        ${{ matrix.dumbass_move }} FurinaImpact.Gameserver/bin/Release/net7.0/* ./build/Server/
        ${{ matrix.dumbass_move }} FurinaImpact.Proxy/bin/Release/net7.0/* ./build/Proxy/
        ${{ matrix.dumbass_move }} ./build ../../

    - name: Compress Build
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: "zip"
        filename: "${{ matrix.asset_name }}.zip"
        path: ./build

    - name: Upload Build
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref }}
        asset_name: "${{ matrix.asset_name }}.zip"
        body: "Another day, another dollar.\n You can get the resources from [here](https://discord.gg/sHZuMpCpVw)."
        overwrite: true
        file: "${{ matrix.asset_name }}.zip"
